version = 0.1
[default.deploy.parameters]
stack_name = "hn-scraper-mailsender"
resolve_s3 = true
s3_prefix = "hn-scraper-mailsender"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
